# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Menu_Conta(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ButSaq = QtWidgets.QPushButton(self.centralwidget)
        self.ButSaq.setGeometry(QtCore.QRect(260, 180, 131, 23))
        self.ButSaq.setObjectName("ButSaq")
        self.ButTrans = QtWidgets.QPushButton(self.centralwidget)
        self.ButTrans.setGeometry(QtCore.QRect(260, 220, 131, 23))
        self.ButTrans.setObjectName("ButTrans")
        self.ButDep = QtWidgets.QPushButton(self.centralwidget)
        self.ButDep.setGeometry(QtCore.QRect(260, 140, 131, 23))
        self.ButDep.setObjectName("ButDep")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 260, 131, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.MenuConta = QtWidgets.QLabel(self.centralwidget)
        self.MenuConta.setGeometry(QtCore.QRect(260, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.MenuConta.setFont(font)
        self.MenuConta.setObjectName("MenuConta")
        self.ButSald = QtWidgets.QPushButton(self.centralwidget)
        self.ButSald.setGeometry(QtCore.QRect(260, 90, 131, 23))
        self.ButSald.setObjectName("ButSald")
        self.ButHome = QtWidgets.QPushButton(self.centralwidget)
        self.ButHome.setGeometry(QtCore.QRect(540, 10, 75, 23))
        self.ButHome.setObjectName("ButHome")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ButSaq.setText(_translate("MainWindow", "Sacar"))
        self.ButDep.setText(_translate("MainWindow", "Depositar"))
        self.pushButton_4.setText(_translate("MainWindow", "Histórico"))
        self.MenuConta.setText(_translate("MainWindow", "Menu Conta"))
        self.ButSald.setText(_translate("MainWindow", "Saldo"))
        self.ButTrans.setText(_translate("MainWindow", "Transferência"))
        self.ButHome.setText(_translate("MainWindow", "Logout"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Menu_Conta()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())