# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saque.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_saque(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SAQUE = QtWidgets.QLabel(self.centralwidget)
        self.SAQUE.setGeometry(QtCore.QRect(240, 80, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SAQUE.setFont(font)
        self.SAQUE.setObjectName("SAQUE")
        self.InpVal = QtWidgets.QLineEdit(self.centralwidget)
        self.InpVal.setGeometry(QtCore.QRect(230, 190, 113, 20))
        self.InpVal.setObjectName("InpVal")
        self.Valor = QtWidgets.QLabel(self.centralwidget)
        self.Valor.setGeometry(QtCore.QRect(170, 190, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Valor.setFont(font)
        self.Valor.setObjectName("Valor")
        self.ButSaque = QtWidgets.QPushButton(self.centralwidget)
        self.ButSaque.setGeometry(QtCore.QRect(240, 250, 91, 41))
        self.ButSaque.setObjectName("ButSaque")
        self.Home = QtWidgets.QPushButton(self.centralwidget)
        self.Home.setGeometry(QtCore.QRect(490, 20, 75, 23))
        self.Home.setObjectName("Home")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 150, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.InpNum = QtWidgets.QLineEdit(self.centralwidget)
        self.InpNum.setGeometry(QtCore.QRect(230, 150, 113, 20))
        self.InpNum.setText("")
        self.InpNum.setObjectName("InpNum")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SAQUE.setText(_translate("MainWindow", "Saque"))
        self.Valor.setText(_translate("MainWindow", "Valor:"))
        self.ButSaque.setText(_translate("MainWindow", "SACAR"))
        self.Home.setText(_translate("MainWindow", "Voltar"))
        self.label.setText(_translate("MainWindow", "Numero:"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_saque()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())