# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_extrato(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Titu = QtWidgets.QLabel(self.centralwidget)
        self.Titu.setGeometry(QtCore.QRect(120, 180, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Titu.setFont(font)
        self.Titu.setObjectName("Titu")
        self.SAQUE = QtWidgets.QLabel(self.centralwidget)
        self.SAQUE.setGeometry(QtCore.QRect(260, 70, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SAQUE.setFont(font)
        self.SAQUE.setObjectName("SAQUE")
        self.OutTit = QtWidgets.QLineEdit(self.centralwidget)
        self.OutTit.setGeometry(QtCore.QRect(250, 180, 221, 20))
        self.OutTit.setObjectName("OutTit")
        self.OutSald = QtWidgets.QLineEdit(self.centralwidget)
        self.OutSald.setGeometry(QtCore.QRect(250, 230, 113, 20))
        self.OutSald.setObjectName("OutSald")
        self.Saldo = QtWidgets.QLabel(self.centralwidget)
        self.Saldo.setGeometry(QtCore.QRect(190, 230, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Saldo.setFont(font)
        self.Saldo.setObjectName("Saldo")
        self.InpNum = QtWidgets.QLineEdit(self.centralwidget)
        self.InpNum.setGeometry(QtCore.QRect(250, 130, 111, 20))
        self.InpNum.setObjectName("InpNum")
        self.numCo = QtWidgets.QLabel(self.centralwidget)
        self.numCo.setGeometry(QtCore.QRect(120, 130, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numCo.setFont(font)
        self.numCo.setObjectName("numCo")
        self.Home = QtWidgets.QPushButton(self.centralwidget)
        self.Home.setGeometry(QtCore.QRect(500, 30, 75, 23))
        self.Home.setObjectName("Home")
        self.ButExtr = QtWidgets.QPushButton(self.centralwidget)
        self.ButExtr.setGeometry(QtCore.QRect(380, 130, 75, 23))
        self.ButExtr.setObjectName("ButExtr")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titu.setText(_translate("MainWindow", "Nome do titular:"))
        self.SAQUE.setText(_translate("MainWindow", "Extrato"))
        self.Saldo.setText(_translate("MainWindow", "Saldo:"))
        self.numCo.setText(_translate("MainWindow", "Número da conta:"))
        self.Home.setText(_translate("MainWindow", "Voltar"))
        self.ButExtr.setText(_translate("MainWindow", "Extrato"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_extrato()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())