# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Acesso(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.OutNom = QtWidgets.QLineEdit(self.centralwidget)
        self.OutNom.setGeometry(QtCore.QRect(190, 60, 221, 20))
        self.OutNom.setObjectName("OutNom")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.InpNum = QtWidgets.QLineEdit(self.centralwidget)
        self.InpNum.setGeometry(QtCore.QRect(240, 160, 113, 20))
        self.InpNum.setObjectName("InpNum")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 160, 47, 21))
        self.label_3.setObjectName("label_3")
        self.ButAcess = QtWidgets.QPushButton(self.centralwidget)
        self.ButAcess.setGeometry(QtCore.QRect(240, 200, 111, 30))
        self.ButAcess.setObjectName("ButAcess")
        self.ButHome = QtWidgets.QPushButton(self.centralwidget)
        self.ButHome.setGeometry(QtCore.QRect(550, 10, 75, 23))
        self.ButHome.setObjectName("ButHome")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Bem vindo Cliente"))
        self.label_2.setText(_translate("MainWindow", "Digite o número da conta que deseja acessar:"))
        self.label_3.setText(_translate("MainWindow", "Número:"))
        self.ButAcess.setText(_translate("MainWindow", "Acessar"))
        self.ButHome.setText(_translate("MainWindow", "Logout"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui =  Tela_Acesso()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())