# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Login = QtWidgets.QLabel(self.centralwidget)
        self.Login.setGeometry(QtCore.QRect(280, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Login.setFont(font)
        self.Login.setObjectName("Login")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 100, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.CPF = QtWidgets.QLabel(self.centralwidget)
        self.CPF.setGeometry(QtCore.QRect(220, 100, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CPF.setFont(font)
        self.CPF.setObjectName("CPF")
        self.ou = QtWidgets.QLabel(self.centralwidget)
        self.ou.setGeometry(QtCore.QRect(310, 130, 21, 16))
        self.ou.setObjectName("ou")
        self.ButCadas = QtWidgets.QPushButton(self.centralwidget)
        self.ButCadas.setGeometry(QtCore.QRect(280, 160, 85, 23))
        self.ButCadas.setObjectName("ButCadas")
        self.ButLogin = QtWidgets.QPushButton(self.centralwidget)
        self.ButLogin.setGeometry(QtCore.QRect(380, 100, 41, 23))
        self.ButLogin.setObjectName("ButLogin")
        self.ButHome = QtWidgets.QPushButton(self.centralwidget)
        self.ButHome.setGeometry(QtCore.QRect(550, 10, 75, 23))
        self.ButHome.setObjectName("ButHome")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Login.setText(_translate("MainWindow", "Login"))
        self.CPF.setText(_translate("MainWindow", "CPF:"))
        self.ou.setText(_translate("MainWindow", "Ou"))
        self.ButCadas.setText(_translate("MainWindow", "Abrir Conta"))
        self.ButLogin.setText(_translate("MainWindow", "Login"))
        self.ButHome.setText(_translate("MainWindow", "HOME"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())